<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ServiceSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('services')->insert([
            [
                'id' => 1,
                'name' => 'Computer Service',
                'user_id' => 1,
                'listing_id' => 1,
                ],
                [
                'id' => 2,
                'name' => 'Mother Board Service',
                'user_id' => 1,
                'listing_id' => 1,
                ],
                [
                'id' => 3,
                'name' => 'Computer Accessories',
                'user_id' => 1,
                'listing_id' => 1,
                ],
                [
                'id' => 4,
                'name' => 'Monitor',
                'user_id' => 1,
                'listing_id' => 1,
                ],
                [
                'id' => 5,
                'name' => 'Dell Laptop',
                'user_id' => 1,
                'listing_id' => 1,
                ],
                [
                'id' => 6,
                'name' => 'OS Installation',
                'user_id' => 1,
                'listing_id' => 1,
                ],
                [
                'id' => 7,
                'name' => 'Software Installation',
                'user_id' => 1,
                'listing_id' => 1,
                ],
                [
                'id' => 8,
                'name' => 'Custom PC Build',
                'user_id' => 1,
                'listing_id' => 1,
                ],
                [
                'id' => 9,
                'name' => 'Gaiming PC',
                'user_id' => 1,
                'listing_id' => 1,
                ],
                [
                'id' => 10,
                'name' => 'Cataract Surgery',
                'user_id' => 1,
                'listing_id' => 2,
                ],
                [
                'id' => 11,
                'name' => 'Paediatric Ophthalmology',
                'user_id' => 1,
                'listing_id' => 2,
                ],
                [
                'id' => 12,
                'name' => 'Emergency Eye Care',
                'user_id' => 1,
                'listing_id' => 2,
                ],
                [
                'id' => 13,
                'name' => 'Neuro Opthalmology',
                'user_id' => 1,
                'listing_id' => 2,
                ],
                [
                'id' => 14,
                'name' => 'Neuro Ophthalmology',
                'user_id' => 1,
                'listing_id' => 2,
                ],
                [
                'id' => 15,
                'name' => 'Computer Vision Syndrome',
                'user_id' => 1,
                'listing_id' => 2,
                ],
                [
                'id' => 16,
                'name' => 'Glaucoma',
                'user_id' => 1,
                'listing_id' => 2,
                ],
                [
                'id' => 17,
                'name' => 'Orbit & Oculoplasty',
                'user_id' => 1,
                'listing_id' => 2,
                ],
                [
                'id' => 18,
                'name' => 'Grocery',
                'user_id' => 1,
                'listing_id' => 3,
                ],
                [
                'id' => 19,
                'name' => 'Furniture',
                'user_id' => 1,
                'listing_id' => 3,
                ],
                [
                'id' => 20,
                'name' => 'Cloths',
                'user_id' => 1,
                'listing_id' => 3,
                ],
                [
                'id' => 21,
                'name' => 'Fruits',
                'user_id' => 1,
                'listing_id' => 3,
                ],
                [
                'id' => 22,
                'name' => 'Vegitables',
                'user_id' => 1,
                'listing_id' => 3,
                ],
                [
                'id' => 23,
                'name' => 'Dry Fruits',
                'user_id' => 1,
                'listing_id' => 3,
                ],
                [
                'id' => 24,
                'name' => 'Fresh Fruits',
                'user_id' => 2,
                'listing_id' => 4,
                ],
                [
                'id' => 25,
                'name' => 'Fresh Chicken Home Delivery',
                'user_id' => 2,
                'listing_id' => 4,
                ],
                [
                'id' => 26,
                'name' => 'Fresh Vegetable Home Delivery',
                'user_id' => 2,
                'listing_id' => 4,
                ],
                [
                'id' => 27,
                'name' => 'Super Fast Home Delivery',
                'user_id' => 2,
                'listing_id' => 4,
                ],
                [
                'id' => 28,
                'name' => 'Fresh Home Delivery',
                'user_id' => 2,
                'listing_id' => 4,
                ],
                [
                'id' => 29,
                'name' => 'Bulk Order',
                'user_id' => 2,
                'listing_id' => 4,
                ],
                [
                'id' => 30,
                'name' => 'Whole Sale',
                'user_id' => 2,
                'listing_id' => 4,
                ],
                [
                'id' => 31,
                'name' => 'Decoration',
                'user_id' => 1,
                'listing_id' => 5,
                ],
                [
                'id' => 32,
                'name' => 'Dinnerwear',
                'user_id' => 1,
                'listing_id' => 5,
                ],
                [
                'id' => 33,
                'name' => 'Furniture',
                'user_id' => 1,
                'listing_id' => 5,
                ],
                [
                'id' => 34,
                'name' => 'Litings',
                'user_id' => 1,
                'listing_id' => 5,
                ],
                [
                'id' => 35,
                'name' => 'Custom Furniture',
                'user_id' => 1,
                'listing_id' => 5,
                ],
                [
                'id' => 36,
                'name' => 'Computer Table',
                'user_id' => 1,
                'listing_id' => 5,
                ],
                [
                'id' => 37,
                'name' => 'Fast Delivery',
                'user_id' => 2,
                'listing_id' => 6,
                ],
                [
                'id' => 38,
                'name' => 'Door Step Delivery',
                'user_id' => 2,
                'listing_id' => 6,
                ],
                [
                'id' => 39,
                'name' => 'Fast Food',
                'user_id' => 2,
                'listing_id' => 6,
                ],
                [
                'id' => 40,
                'name' => 'Italian Food',
                'user_id' => 2,
                'listing_id' => 6,
                ],
                [
                'id' => 41,
                'name' => 'Bulk order',
                'user_id' => 2,
                'listing_id' => 6,
                ],
                [
                'id' => 42,
                'name' => 'Event orders',
                'user_id' => 2,
                'listing_id' => 6,
                ],
                [
                'id' => 43,
                'name' => 'Fresh Fruits',
                'user_id' => 1,
                'listing_id' => 7,
                ],
                [
                'id' => 44,
                'name' => 'Fresh Chicken Home Delivery',
                'user_id' => 1,
                'listing_id' => 7,
                ],
                [
                'id' => 45,
                'name' => 'Fresh Vegetable Home Delivery',
                'user_id' => 1,
                'listing_id' => 7,
                ],
                [
                'id' => 46,
                'name' => 'Super Fast Home Delivery',
                'user_id' => 1,
                'listing_id' => 7,
                ],
                [
                'id' => 47,
                'name' => 'Fresh Home Delivery',
                'user_id' => 1,
                'listing_id' => 7,
                ],
                [
                'id' => 48,
                'name' => 'Whole Sale',
                'user_id' => 1,
                'listing_id' => 7,
                ],
                [
                'id' => 49,
                'name' => 'Fresh Fruits',
                'user_id' => 1,
                'listing_id' => 14,
                ],
                [
                'id' => 50,
                'name' => 'Fresh Chicken Home Delivery',
                'user_id' => 1,
                'listing_id' => 14,
                ],
                [
                'id' => 51,
                'name' => 'Fresh Vegetable Home Delivery',
                'user_id' => 1,
                'listing_id' => 14,
                ],
                [
                'id' => 52,
                'name' => 'Super Fast Home Delivery',
                'user_id' => 1,
                'listing_id' => 14,
                ],
                [
                'id' => 53,
                'name' => 'Fresh Home Delivery',
                'user_id' => 1,
                'listing_id' => 14,
                ],
                [
                'id' => 54,
                'name' => 'Bulk Order',
                'user_id' => 1,
                'listing_id' => 14,
                ],
                [
                'id' => 55,
                'name' => 'Whole Sale',
                'user_id' => 1,
                'listing_id' => 14,
                ],
                [
                'id' => 56,
                'name' => 'Fast Delivery',
                'user_id' => 1,
                'listing_id' => 12,
                ],
                [
                'id' => 57,
                'name' => 'Door Step Delivery',
                'user_id' => 1,
                'listing_id' => 12,
                ],
                [
                'id' => 58,
                'name' => 'Fast Food',
                'user_id' => 1,
                'listing_id' => 12,
                ],
                [
                'id' => 59,
                'name' => 'Italian Food',
                'user_id' => 1,
                'listing_id' => 12,
                ],
                [
                'id' => 60,
                'name' => 'Bulk order',
                'user_id' => 1,
                'listing_id' => 12,
                ],
                [
                'id' => 61,
                'name' => 'Event orders',
                'user_id' => 1,
                'listing_id' => 12,
                ],
                [
                'id' => 62,
                'name' => 'Decoration',
                'user_id' => 1,
                'listing_id' => 11,
                ],
                [
                'id' => 63,
                'name' => 'Dinnerwear',
                'user_id' => 1,
                'listing_id' => 11,
                ],
                [
                'id' => 64,
                'name' => 'Furniture',
                'user_id' => 1,
                'listing_id' => 11,
                ],
                [
                'id' => 65,
                'name' => 'Litings',
                'user_id' => 1,
                'listing_id' => 11,
                ],
                [
                'id' => 66,
                'name' => 'Custom Furniture',
                'user_id' => 1,
                'listing_id' => 11,
                ],
                [
                'id' => 67,
                'name' => 'Computer Table',
                'user_id' => 1,
                'listing_id' => 11,
                ],
                [
                'id' => 68,
                'name' => 'Computer Service',
                'user_id' => 1,
                'listing_id' => 8,
                ],
                [
                'id' => 69,
                'name' => 'Mother Board Service',
                'user_id' => 1,
                'listing_id' => 8,
                ],
                [
                'id' => 70,
                'name' => 'Computer Accessories',
                'user_id' => 1,
                'listing_id' => 8,
                ],
                [
                'id' => 71,
                'name' => 'Monitor',
                'user_id' => 1,
                'listing_id' => 8,
                ],
                [
                'id' => 72,
                'name' => 'Dell Laptop',
                'user_id' => 1,
                'listing_id' => 8,
                ],
                [
                'id' => 73,
                'name' => 'OS Installation',
                'user_id' => 1,
                'listing_id' => 8,
                ],
                [
                'id' => 74,
                'name' => 'Software Installation',
                'user_id' => 1,
                'listing_id' => 8,
                ],
                [
                'id' => 75,
                'name' => 'Custom PC Build',
                'user_id' => 1,
                'listing_id' => 8,
                ],
                [
                'id' => 76,
                'name' => 'Gaiming PC',
                'user_id' => 1,
                'listing_id' => 8,
                ],
                [
                'id' => 77,
                'name' => 'Computer Service',
                'user_id' => 2,
                'listing_id' => 13,
                ],
                [
                'id' => 78,
                'name' => 'Mother Board Service',
                'user_id' => 2,
                'listing_id' => 13,
                ],
                [
                'id' => 79,
                'name' => 'Computer Accessories',
                'user_id' => 2,
                'listing_id' => 13,
                ],
                [
                'id' => 80,
                'name' => 'Monitor',
                'user_id' => 2,
                'listing_id' => 13,
                ],
                [
                'id' => 81,
                'name' => 'Dell Laptop',
                'user_id' => 2,
                'listing_id' => 13,
                ],
                [
                'id' => 82,
                'name' => 'OS Installation',
                'user_id' => 2,
                'listing_id' => 13,
                ],
                [
                'id' => 83,
                'name' => 'Software Installation',
                'user_id' => 2,
                'listing_id' => 13,
                ],
                [
                'id' => 84,
                'name' => 'Custom PC Build',
                'user_id' => 2,
                'listing_id' => 13,
                ],
                [
                'id' => 85,
                'name' => 'Gaiming PC',
                'user_id' => 2,
                'listing_id' => 13,
                ],
                [
                'id' => 86,
                'name' => 'Fast Delivery',
                'user_id' => 2,
                'listing_id' => 10,
                ],
                [
                'id' => 87,
                'name' => 'Door Step Delivery',
                'user_id' => 2,
                'listing_id' => 10,
                ],
                [
                'id' => 88,
                'name' => 'Fast Food',
                'user_id' => 2,
                'listing_id' => 10,
                ],
                [
                'id' => 89,
                'name' => 'Italian Food',
                'user_id' => 2,
                'listing_id' => 10,
                ],
                [
                'id' => 90,
                'name' => 'Bulk order',
                'user_id' => 2,
                'listing_id' => 10,
                ],
                [
                'id' => 91,
                'name' => 'Event orders',
                'user_id' => 2,
                'listing_id' => 10,
                ],
                [
                'id' => 92,
                'name' => 'Cataract Surgery',
                'user_id' => 2,
                'listing_id' => 9,
                ],
                [
                'id' => 93,
                'name' => 'Paediatric Ophthalmology',
                'user_id' => 2,
                'listing_id' => 9,
                ],
                [
                'id' => 94,
                'name' => 'Emergency Eye Care',
                'user_id' => 2,
                'listing_id' => 9,
                ],
                [
                'id' => 95,
                'name' => 'Neuro Opthalmology',
                'user_id' => 2,
                'listing_id' => 9,
                ],
                [
                'id' => 96,
                'name' => 'Neuro Ophthalmology',
                'user_id' => 2,
                'listing_id' => 9,
                ],
                [
                'id' => 97,
                'name' => 'Computer Vision Syndrome',
                'user_id' => 2,
                'listing_id' => 9,
                ],
                [
                'id' => 98,
                'name' => 'Glaucoma',
                'user_id' => 2,
                'listing_id' => 9,
                ],
                [
                'id' => 99,
                'name' => 'Orbit & Oculoplasty',
                'user_id' => 2,
                'listing_id' => 9,
            ],
        ]);
    }
}
